# Generated by Django 4.0.2 on 2022-02-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPU_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('eth', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('ton', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('day_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('month_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('primary_token', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Type of GPU',
                'verbose_name_plural': 'Types of GPU',
            },
        ),
    ]
